#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keystoneauth1
Version  : 1.1.0
Release  : 2
URL      : https://pypi.python.org/packages/source/k/keystoneauth1/keystoneauth1-1.1.0.tar.gz
Source0  : https://pypi.python.org/packages/source/k/keystoneauth1/keystoneauth1-1.1.0.tar.gz
Summary  : Authentication Library for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: keystoneauth1-python
BuildRequires : Sphinx-python
BuildRequires : WebOb-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : hacking
BuildRequires : iso8601-python
BuildRequires : keyring-python
BuildRequires : mox3-python
BuildRequires : oauthlib-python
BuildRequires : oslo.config
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pycrypto-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : stevedore
BuildRequires : tempest-lib-python
BuildRequires : testrepository-python
BuildRequires : testresources
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
===============================
keystoneauth
===============================
Authentication Library for OpenStack Clients

%package python
Summary: python components for the keystoneauth1 package.
Group: Default
Requires: six-python
Requires: requests-python
Requires: iso8601-python

%description python
python components for the keystoneauth1 package.


%prep
%setup -q -n keystoneauth1-1.1.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
