#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keystoneauth1
Version  : 2.19.0
Release  : 29
URL      : https://pypi.debian.net/keystoneauth1/keystoneauth1-2.19.0.tar.gz
Source0  : https://pypi.debian.net/keystoneauth1/keystoneauth1-2.19.0.tar.gz
Summary  : Authentication Library for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: keystoneauth1-python
Requires: fixtures
Requires: iso8601
Requires: lxml
Requires: oauthlib
Requires: pbr
Requires: positional
Requires: python-mock
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
This directory holds the betamax test cassettes that are pre-generated
for unit testing. This can be removed in the future with a functional
test that stands up a full devstack, records a cassette and then
replays it as part of the test suite.

%package python
Summary: python components for the keystoneauth1 package.
Group: Default

%description python
python components for the keystoneauth1 package.


%prep
%setup -q -n keystoneauth1-2.19.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492438360
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492438360
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
