#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keystoneauth1
Version  : 3.10.0
Release  : 35
URL      : https://pypi.debian.net/keystoneauth1/keystoneauth1-3.10.0.tar.gz
Source0  : https://pypi.debian.net/keystoneauth1/keystoneauth1-3.10.0.tar.gz
Summary  : Authentication Library for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: keystoneauth1-python3
Requires: keystoneauth1-license
Requires: keystoneauth1-python
Requires: PyYAML
Requires: Sphinx
Requires: bandit
Requires: coverage
Requires: fixtures
Requires: flake8-docstrings
Requires: hacking
Requires: iso8601
Requires: lxml
Requires: oauthlib
Requires: os-testr
Requires: oslo.config
Requires: oslo.utils
Requires: oslotest
Requires: pbr
Requires: python-mock
Requires: reno
Requires: requests
Requires: requests-mock
Requires: six
Requires: stevedore
Requires: testresources
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package license
Summary: license components for the keystoneauth1 package.
Group: Default

%description license
license components for the keystoneauth1 package.


%package python
Summary: python components for the keystoneauth1 package.
Group: Default
Requires: keystoneauth1-python3

%description python
python components for the keystoneauth1 package.


%package python3
Summary: python3 components for the keystoneauth1 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the keystoneauth1 package.


%prep
%setup -q -n keystoneauth1-3.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532294047
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/keystoneauth1
cp LICENSE %{buildroot}/usr/share/doc/keystoneauth1/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/keystoneauth1/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
